# Generated by Django 4.1.2 on 2022-12-07 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0015_auto_20221206_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundador',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 46, 58, 97603)),
        ),
        migrations.AlterField(
            model_name='fundador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fundador',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 46, 58, 97603)),
        ),
    ]
