# Generated by Django 4.1.2 on 2022-12-07 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0016_alter_fundador_created_alter_fundador_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundador',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 51, 16, 857369)),
        ),
        migrations.AlterField(
            model_name='fundador',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 51, 16, 857369)),
        ),
    ]
